site_name: Homemade Conslaws

docs_dir: "build"

theme:
  name: material
  palette:
    # scheme: conslaws
    - media: "(prefers-color-scheme: dark)"
      scheme: conslaws-dark
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: light)"
      scheme: conslaws-light
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # primary: custom
  features:
    - content.tabs.link # Proof and theorem/lemma/... are on the same tab
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky


nav:
  - Conservation Laws: "index.md"
  - Theory:
    - Linear transport equations: "theory/linear_transport_eqs.md"
    - Scalar conservation laws: "theory/scalar_cons_laws.md"
    - Finite volume schemes: "theory/finite_volume_schemes.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

extra_css:
  - stylesheets/palettes.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js