site_name: Homemade Conslaws

docs_dir: "build"

theme:
  name: material
  palette:
    # scheme: conslaws
    - media: "(prefers-color-scheme: dark)"
      scheme: conslaws-dark
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: light)"
      scheme: conslaws-light
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # primary: custom
  features:
    - content.tabs.link # Proof and theorem/lemma/... are on the same tab
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky


nav:
  - index.md
  - Theory:
    - theory/index.md
    - Linear transport equations: "theory/linear_transport_eqs.md"
    - Scalar conservation laws: "theory/scalar_cons_laws.md"
    - Finite volume schemes: "theory/finite_volume_schemes.md"
    - Second order schemes: "theory/2nd_order_schemes.md"
    - Nonlinear hyperbolic systems in one dimension: "theory/nonlinear_hyperbolic_systems.md"
  - Final Report: "final_report.md"
  - Docs:
    - docs/index.md
    - Equation: "docs/equation.md"
    - Grid: "docs/grid.md"
    - Boundary condition: "docs/bc.md"
    - Numerical flux: "docs/numerical_flux.md"
    - Reconstruction: "docs/reconstruction.md"
    - Time stepper: "docs/timestepper.md"
    - Simulator: "docs/simulator.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes

extra_css:
  - stylesheets/palettes.css
  - stylesheets/admonitions/theorem.css
  - stylesheets/admonitions/lemma.css
  - stylesheets/admonitions/definition.css
  - stylesheets/admonitions/proof.css

extra_javascript:
  - javascripts/math_tooltips.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js