site_name: Homemade Conslaws

docs_dir: "build"

theme:
  name: material
  features:
    - content.tabs.link # Proof and theorem/lemma/... are on the same tab
    - navigation.instant

nav:
  - Conservation Laws: "index.md"
  - Theory:
    - Linear transport equations: "theory/linear_transport_eqs.md"
    - Scalar conservation laws: "theory/scalar_cons_laws.md"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js