name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1'

    - name: Install dependencies
      run: |
        julia -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'

    - name: Run tests with coverage
      run: |
        julia -e 'using Pkg; Pkg.activate("."); Pkg.add("Coverage"); Pkg.test(coverage=true)'

    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true